### ISSUE TITLE
Issues including library as dependency with CMake

### ISSUE THREAD

**Issue by claudious96** [neXenio/panoptes#1]
Hi! First of all, thanks for the great work!

I'm trying to include panoptes as a dependecy in a c++ project, I'm trying to include it using CMake (since could be a cross platform project I wanted to avoid the hustle of using conan on different platforms).

In order to include it automatically at configure time, in my CMakeLists.txt I've written
```
FetchContent_Declare(
        panoptes
        GIT_REPOSITORY https://github.com/neXenio/panoptes.git
        GIT_TAG        v1.0
)
FetchContent_MakeAvailable(panoptes)
```
However when it comes to building the library, CMake looks for `src/` and `console/` in the root project directory instead of the subdir inside the build dir.
Having a look at these lines in [CMakeLists.txt](https://github.com/neXenio/panoptes/blob/master/CMakeLists.txt#L40) (#40-45) and changing the CMake variables `${CMAKE_SOURCE_DIR}` to `${CMAKE_CURRENT_SOURCE_DIR}` builds correctly.

I'm not sure if that's the best way to include the project, I'm obviously open to any advice.
[Here](https://pastebin.com/Jc625pYH) is my CMakeLists.txt that works with the fix mentioned above, the CMake version is 3.16.3.

**Comment by Trafo** [comment]
@claudious96 Sorry for the late replay and thx for telling us your issue. Can you apply a pull request? I guess it is good to use  ```${CMAKE_CURRENT_SOURCE_DIR}``` because in your case it just works and in other cases, it does not hurt.
