### ISSUE TITLE
Memory Leak in InotifyEventLoop on Linux

### ISSUE THREAD

**Issue by baltendorf** [neXenio/panoptes#5]
The usage of strdup() in InotifyEventLoop on Linux causes a memory leak.

The strdup() function returns a pointer to a new string which is  a duplicate of the string s. 
Memory for the new string is obtained with malloc, and have to be freed with free (see [strdup(3)](https://man7.org/linux/man-pages/man3/strdup.3.html).

**Comment by Trafo** [comment]
Thx for reporting this bug. This bug should be solved with version 1.0.4.
