### ISSUE TITLE
Memory Leak in InotifyTree on Linux

### ISSUE THREAD

**Issue by baltendorf** [neXenio/panoptes#6]
It seems, that mInotifyNodeByWatchDescriptor, allocated with new at InotifyTree.cpp:12 was never freed.

`Direct leak of 3744 byte(s) in 78 object(s) allocated from:
    #0 0x7f2324b7c947 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
    #1 0x559aa1714153 in NSFW::InotifyTree::InotifyTree(int, boost::filesystem::path const&, std::shared_ptr<NSFW::Collector>) /home/templer/Devel/Libs/nsfw/src/linux/InotifyTree.cpp:12

`

**Comment by Trafo** [comment]
Thx for reporting this bug. The issue should be solved with version 1.0.4.
